language: c

os:
    - linux
    - osx

osx_image: xcode8

compiler:
    - gcc
    - clang

env:
    - EDITOR=true
    - PAGER=true

sudo: true

script:
    - make
    - sudo make install
    - perl test/check.pl
