language: c

os:
    - linux
    - osx

dist: trusty

# Older OSX version to support valgrind
osx_image: xcode6.4

compiler:
    - gcc
    - clang

env:
    - EDITOR=true PAGER=true

sudo: required

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install valgrind; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi

script:
    - make
    - sudo make install
    - perl test/check.pl
