language: c

os:
    - linux
    - osx

osx_image: xcode8

compiler:
    - gcc
    - clang

env:
    - EDITOR=true PAGER=true

sudo: true

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install valgrind; fi

script:
    - make
    - sudo make install
    - perl test/check.pl
