language: c

os:
    - linux
    - osx

osx_image: xcode8

compiler:
    - gcc
    - clang

sudo: true

script:
    - make
    - sudo make install
    - sm -a -n test -f test/test.pl -D 'test file'
    - perl test/check.pl
